### ISSUE TITLE
Inquiry Regarding Budget for Utilizing OpenAI GPT-3

### ISSUE THREAD

**Issue by maxwellyin** [itsnamgyu/reasoning-teacher#13]
Hi,

Thanks for the release of the code and data associated with your paper. The work significantly contributes to establishing a robust foundation for future research on KD and CoT methods. I am keen on following your work, yet I am uncertain about the sufficiency of my budget. You mention that the cost exceeds $1000 (USD?) to obtain the data. I just wonder whether this figure represents the cumulative cost for conducting the experiments over a specified duration, or is it associated with a single iteration of the process?

Best,
Maxwell

**Comment by itsnamgyu** [comment]
Hi, the total cost of inference exceeded $1000 USD, and the overall total cost, which includes fine-tuning, was approximately $2000 USD (please check our paper for the exact figure).

Model availability and pricing has since changed in the OpenAI API, so I would recommend that you check out their new pricing. You can estimate the cost of your own experiments by counting the number of tokens in your dataset (i.e., question prompts) and expected inference tokens.
