### ISSUE TITLE
Lack of dataset for teacher completion data

### ISSUE THREAD

**Issue by maxwellyin** [itsnamgyu/reasoning-teacher#15]
Hi,

I've noticed in your paper, you mentioned that you used 12 datasets. However, I have found only 9 in the teacher completion data folder. Could you please confirm if the remaining datasets are located elsewhere or if there was an oversight?

Thank you for your attention to this matter.

Best regards,
Maxwell

**Comment by itsnamgyu** [comment]
Hi, if you are referring to the "diverse reasoning" completion data using temperature 0.7 in the `B_text-davinci-002__C_zs_cot_t70` directory, we omitted some datasets because they were too large and it would be too costly to obtain multiple answers (per question) for those datasets.

The `B_text-davinci-002__C_zs_cot` directory contains completion data for all datasets (single answer using greedy sampling)
